"""
Antigravity Auto-Retry Clicker
==============================
Tự động nhấn nút Retry khi Antigravity gặp lỗi "Agent terminated due to error"
hoặc "Our servers are experiencing high traffic".

Features:
  - Quét màn hình theo interval để tìm nút Retry
  - Tự động click khi phát hiện
  - System tray icon với menu start/stop/quit
  - Hotkey toggle (F6) và quit (F7)
  - Sound notification khi click
  - Log file chi tiết
  - Thống kê số lần retry

Usage:
    python autoclick.py

Author: Auto-generated by Antigravity
"""

import pyautogui
import json
import os
import sys
import time
import threading
import logging
from datetime import datetime

try:
    import winsound
    HAS_WINSOUND = True
except ImportError:
    HAS_WINSOUND = False
from pathlib import Path

# Tắt fail-safe nếu cần (cẩn thận!)
# pyautogui.FAILSAFE = True  # Giữ True để có thể dừng bằng cách di chuột vào góc

# ============================================================================
# CONFIGURATION
# ============================================================================

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
CONFIG_FILE = os.path.join(SCRIPT_DIR, "config.json")

DEFAULT_CONFIG = {
    "scan_interval_seconds": 3,
    "confidence": 0.8,
    "click_delay_seconds": 0.5,
    "max_retries_per_session": 0,  # 0 = unlimited
    "hotkey_toggle": "F6",
    "hotkey_quit": "F7",
    "sound_enabled": True,
    "log_file": "autoclick.log",
    "button_images": [
        "images/retry_button.png",
        "images/retry_button_large.png",
    ],
}


def load_config():
    """Load config from file or use defaults."""
    config = DEFAULT_CONFIG.copy()
    if os.path.exists(CONFIG_FILE):
        try:
            with open(CONFIG_FILE, "r", encoding="utf-8") as f:
                user_config = json.load(f)
                config.update(user_config)
        except Exception as e:
            print(f"⚠️  Lỗi đọc config: {e}, sử dụng config mặc định")
    return config


# ============================================================================
# LOGGER
# ============================================================================


def setup_logger(log_file):
    """Setup logging to both file and console."""
    logger = logging.getLogger("AutoClick")
    logger.setLevel(logging.DEBUG)

    # File handler
    log_path = os.path.join(SCRIPT_DIR, log_file)
    fh = logging.FileHandler(log_path, encoding="utf-8")
    fh.setLevel(logging.DEBUG)

    # Console handler
    ch = logging.StreamHandler(sys.stdout)
    ch.setLevel(logging.INFO)

    # Formatter
    fmt = logging.Formatter(
        "%(asctime)s [%(levelname)s] %(message)s", datefmt="%Y-%m-%d %H:%M:%S"
    )
    fh.setFormatter(fmt)
    ch.setFormatter(fmt)

    logger.addHandler(fh)
    logger.addHandler(ch)

    return logger


# ============================================================================
# AUTO CLICKER
# ============================================================================


class AntigravityAutoRetry:
    """Main auto-retry clicker class."""

    def __init__(self):
        self.config = load_config()
        self.logger = setup_logger(self.config["log_file"])
        self.running = False
        self.scanning = False
        self.retry_count = 0
        self.session_start = None
        self.last_click_time = None
        self._stop_event = threading.Event()
        self._scan_thread = None

        # Validate button images exist
        self.button_images = []
        for img_path in self.config["button_images"]:
            full_path = os.path.join(SCRIPT_DIR, img_path)
            if os.path.exists(full_path):
                self.button_images.append(full_path)
                self.logger.info(f"✅ Loaded image: {img_path}")
            else:
                self.logger.warning(f"⚠️  Image not found: {full_path}")

        if not self.button_images:
            self.logger.error(
                "❌ Không tìm thấy ảnh nút Retry! "
                "Chạy 'python capture_button.py' để chụp ảnh nút trước."
            )

    def play_sound(self, sound_type="click"):
        """Play notification sound."""
        if not self.config.get("sound_enabled", True):
            return
            
        if HAS_WINSOUND:
            try:
                if sound_type == "click":
                    winsound.Beep(1000, 200)
                elif sound_type == "start":
                    winsound.Beep(800, 150)
                    winsound.Beep(1200, 150)
                elif sound_type == "stop":
                    winsound.Beep(1200, 150)
                    winsound.Beep(800, 150)
            except Exception:
                pass
        elif sys.platform == "darwin":
            # Native macOS sounds using afplay
            try:
                if sound_type == "click":
                    os.system("afplay /System/Library/Sounds/Ping.aiff &")
                elif sound_type == "start":
                    os.system("afplay /System/Library/Sounds/Glass.aiff &")
                elif sound_type == "stop":
                    os.system("afplay /System/Library/Sounds/Basso.aiff &")
            except Exception:
                pass

    def find_retry_button(self):
        """Tìm nút Retry trên màn hình."""
        confidence = self.config["confidence"]

        for img_path in self.button_images:
            try:
                location = pyautogui.locateCenterOnScreen(
                    img_path, confidence=confidence
                )
                if location:
                    self.logger.debug(
                        f"Found button at ({location.x}, {location.y}) "
                        f"using {os.path.basename(img_path)}"
                    )
                    return location
            except pyautogui.ImageNotFoundException:
                continue
            except Exception as e:
                self.logger.debug(f"Error scanning with {img_path}: {e}")
                continue

        return None

    def click_retry(self, location):
        """Click nút Retry tại vị trí đã tìm."""
        delay = self.config["click_delay_seconds"]

        self.logger.info(
            f"🎯 Phát hiện nút Retry tại ({location.x}, {location.y})!"
        )

        # Đợi một chút trước khi click (đề phòng dialog chưa ổn định)
        time.sleep(delay)

        # Verify lại vị trí (dialog có thể đã biến mất)
        verify_location = self.find_retry_button()
        if verify_location is None:
            self.logger.info("ℹ️  Dialog đã biến mất trước khi click, bỏ qua.")
            return False

        # Click!
        pyautogui.click(verify_location.x, verify_location.y)

        self.retry_count += 1
        self.last_click_time = datetime.now()

        self.logger.info(
            f"🔄 Đã click Retry! (Lần thứ {self.retry_count} trong session)"
        )
        self.play_sound("click")

        return True

    def scan_loop(self):
        """Main scanning loop."""
        interval = self.config["scan_interval_seconds"]
        max_retries = self.config["max_retries_per_session"]

        self.logger.info(f"🔍 Bắt đầu quét (mỗi {interval}s)...")

        while not self._stop_event.is_set():
            # Check max retries
            if max_retries > 0 and self.retry_count >= max_retries:
                self.logger.info(
                    f"⏹️  Đã đạt giới hạn {max_retries} lần retry. Dừng quét."
                )
                self.scanning = False
                break

            # Scan for retry button
            try:
                location = self.find_retry_button()
                if location:
                    self.click_retry(location)

                    # Đợi thêm sau khi click để Antigravity xử lý
                    cooldown = max(5, interval * 2)
                    self.logger.info(
                        f"⏳ Cooldown {cooldown}s sau khi click..."
                    )
                    self._stop_event.wait(cooldown)
                else:
                    self.logger.debug("Không tìm thấy nút Retry.")
            except Exception as e:
                self.logger.error(f"❌ Lỗi khi quét: {e}")

            # Wait for next scan
            self._stop_event.wait(interval)

        self.logger.info("⏹️  Đã dừng quét.")

    def start(self):
        """Start scanning."""
        if self.scanning:
            self.logger.info("ℹ️  Đang quét rồi!")
            return

        if not self.button_images:
            self.logger.error(
                "❌ Không có ảnh nút Retry! Chạy 'python capture_button.py' trước."
            )
            return

        self.scanning = True
        self.running = True
        self.session_start = datetime.now()
        self._stop_event.clear()

        self._scan_thread = threading.Thread(target=self.scan_loop, daemon=True)
        self._scan_thread.start()

        self.play_sound("start")
        self.logger.info("▶️  Auto-Retry đã bật!")

    def stop(self):
        """Stop scanning."""
        if not self.scanning:
            self.logger.info("ℹ️  Chưa quét!")
            return

        self.scanning = False
        self._stop_event.set()

        if self._scan_thread:
            self._scan_thread.join(timeout=5)

        self.play_sound("stop")
        self.logger.info(
            f"⏹️  Auto-Retry đã tắt. Tổng retry: {self.retry_count}"
        )

    def toggle(self):
        """Toggle scanning on/off."""
        if self.scanning:
            self.stop()
        else:
            self.start()

    def get_stats(self):
        """Get statistics."""
        uptime = ""
        if self.session_start:
            delta = datetime.now() - self.session_start
            hours, remainder = divmod(int(delta.total_seconds()), 3600)
            minutes, seconds = divmod(remainder, 60)
            uptime = f"{hours:02d}:{minutes:02d}:{seconds:02d}"

        return {
            "scanning": self.scanning,
            "retry_count": self.retry_count,
            "session_start": (
                self.session_start.strftime("%H:%M:%S") if self.session_start else "N/A"
            ),
            "uptime": uptime or "N/A",
            "last_click": (
                self.last_click_time.strftime("%H:%M:%S")
                if self.last_click_time
                else "N/A"
            ),
        }


# ============================================================================
# SYSTEM TRAY (Optional - runs if pystray is available)
# ============================================================================


def create_tray_icon(clicker):
    """Create system tray icon (optional)."""
    try:
        import pystray
        from PIL import Image, ImageDraw, ImageFont

        def create_icon_image(active=False):
            """Create a simple tray icon."""
            size = 64
            img = Image.new("RGBA", (size, size), (0, 0, 0, 0))
            draw = ImageDraw.Draw(img)

            # Background circle
            bg_color = (76, 175, 80, 255) if active else (158, 158, 158, 255)
            draw.ellipse([4, 4, size - 4, size - 4], fill=bg_color)

            # "R" letter
            try:
                font = ImageFont.truetype("arial.ttf", 32)
            except Exception:
                font = ImageFont.load_default()

            draw.text(
                (size // 2, size // 2),
                "R",
                fill=(255, 255, 255, 255),
                font=font,
                anchor="mm",
            )
            return img

        def on_toggle(icon, item):
            clicker.toggle()
            icon.icon = create_icon_image(clicker.scanning)
            icon.title = f"AutoRetry - {'ON' if clicker.scanning else 'OFF'}"

        def on_stats(icon, item):
            stats = clicker.get_stats()
            print("\n" + "=" * 40)
            print("  📊 THỐNG KÊ")
            print("=" * 40)
            print(f"  Trạng thái:  {'🟢 Đang quét' if stats['scanning'] else '🔴 Đã dừng'}")
            print(f"  Số lần retry: {stats['retry_count']}")
            print(f"  Bắt đầu:     {stats['session_start']}")
            print(f"  Uptime:       {stats['uptime']}")
            print(f"  Click cuối:   {stats['last_click']}")
            print("=" * 40 + "\n")

        def on_quit(icon, item):
            clicker.stop()
            icon.stop()

        menu = pystray.Menu(
            pystray.MenuItem(
                lambda item: f"{'⏹ Dừng' if clicker.scanning else '▶ Bắt đầu'}",
                on_toggle,
                default=True,
            ),
            pystray.MenuItem("📊 Thống kê", on_stats),
            pystray.Menu.SEPARATOR,
            pystray.MenuItem("❌ Thoát", on_quit),
        )

        icon = pystray.Icon(
            "AutoRetry",
            create_icon_image(False),
            "AutoRetry - OFF",
            menu,
        )

        return icon

    except ImportError:
        return None


# ============================================================================
# CONSOLE UI
# ============================================================================


def print_banner():
    """Print startup banner."""
    banner = """
╔══════════════════════════════════════════════════════════════╗
║                                                              ║
║     🔄  ANTIGRAVITY AUTO-RETRY CLICKER  🔄                  ║
║                                                              ║
║     Tự động nhấn Retry khi Antigravity bị lỗi               ║
║                                                              ║
╠══════════════════════════════════════════════════════════════╣
║                                                              ║
║     Phím tắt:                                                ║
║       F6  -  Bật/Tắt quét                                   ║
║       F7  -  Thoát chương trình                              ║
║                                                              ║
║     Lệnh console:                                            ║
║       start   -  Bắt đầu quét                               ║
║       stop    -  Dừng quét                                   ║
║       stats   -  Xem thống kê                                ║
║       quit    -  Thoát                                       ║
║                                                              ║
╚══════════════════════════════════════════════════════════════╝
"""
    print(banner)


def run_console(clicker):
    """Run console input loop."""
    while clicker.running:
        try:
            cmd = input("\n>>> ").strip().lower()

            if cmd in ("start", "s"):
                clicker.start()
            elif cmd in ("stop", "p"):
                clicker.stop()
            elif cmd in ("toggle", "t"):
                clicker.toggle()
            elif cmd in ("stats", "i"):
                stats = clicker.get_stats()
                print(f"\n  Trạng thái:   {'🟢 ON' if stats['scanning'] else '🔴 OFF'}")
                print(f"  Số lần retry: {stats['retry_count']}")
                print(f"  Uptime:       {stats['uptime']}")
                print(f"  Click cuối:   {stats['last_click']}")
            elif cmd in ("quit", "q", "exit"):
                clicker.stop()
                clicker.running = False
                print("\n👋 Tạm biệt!")
                break
            elif cmd == "help":
                print("\n  start/s  - Bắt đầu quét")
                print("  stop/p   - Dừng quét")
                print("  toggle/t - Bật/Tắt")
                print("  stats/i  - Thống kê")
                print("  quit/q   - Thoát")
            elif cmd:
                print("  ❓ Lệnh không hợp lệ. Gõ 'help' để xem danh sách lệnh.")

        except (KeyboardInterrupt, EOFError):
            clicker.stop()
            clicker.running = False
            print("\n👋 Tạm biệt!")
            break


# ============================================================================
# MAIN
# ============================================================================


def main():
    print_banner()

    clicker = AntigravityAutoRetry()

    # Setup hotkeys (Windows only - macOS requires sudo for global hotkeys)
    if sys.platform != "darwin":
        try:
            import keyboard

            hotkey_toggle = clicker.config["hotkey_toggle"]
            hotkey_quit = clicker.config["hotkey_quit"]

            keyboard.add_hotkey(hotkey_toggle, clicker.toggle)
            keyboard.add_hotkey(
                hotkey_quit,
                lambda: (clicker.stop(), setattr(clicker, "running", False)),
            )

            print(f"  ⌨️  Hotkey: {hotkey_toggle} = Toggle, {hotkey_quit} = Quit")
        except ImportError:
            print("  ⚠️  Module 'keyboard' không có, hotkey bị tắt.")
        except Exception as e:
            print(f"  ⚠️  Không thể đăng ký hotkey: {e}")
    else:
        print("  ℹ️  Global Hotkeys đã bị vô hiệu hóa trên Mac (Do yêu cầu root/sudo).")
        print("      Bạn hãy dùng lệnh ở Terminal (gõ chữ 's' rồi Enter) để tương tác nhé!")

    # Try to create tray icon
    tray_icon = create_tray_icon(clicker)

    if tray_icon:
        # Run tray in background thread
        tray_thread = threading.Thread(target=tray_icon.run, daemon=True)
        tray_thread.start()
        print("  🔔 System tray icon đã tạo.")

    print()
    print("  Gõ 'start' để bắt đầu quét, hoặc nhấn F6")
    print()

    # Auto-start scanning
    auto_start = input("  Bắt đầu quét ngay? (y/n, mặc định y): ").strip().lower()
    if auto_start != "n":
        clicker.start()

    # Run console
    run_console(clicker)

    # Cleanup
    if tray_icon:
        tray_icon.stop()

    sys.exit(0)


if __name__ == "__main__":
    main()
